1)  What is an operating system?
   
    The operating system is a software program that facilitates computer hardware to 
    communicate and operate with the computer software.

2)  What is the main purpose of an operating system?

   It is designed to make sure that a computer system performs well by managing its computational activities.
   It provides an environment for the development and execution of programs.

3)  What is a socket?
   A socket is used to make connection between two applications. 
   Endpoints of the connection are called socket.

4) What is kernel ?

   kernel is the core and most important part of operating system and it provides basic services for all parts
   of Operating system.

5) What is a process?
   An executing program is known as process. There are two types of processes:  
   Operating System Processes
   User Processes

6) What are the different states of a process?
   
   A list of different states of process:
      New Process
      Running Process
      Waiting Process
      Ready Process
      Terminated Process
7) What is the use of paging in operating system?
    
    Paging is used to solve the external fragmentation problem in operating system. 
    This technique ensures that the data you need is available as quickly as possible.

8)  What is virtual memory?
    Virtual memory is a very useful memory management technique which enables processes
     to execute outside of memory. This technique is especially
    used when an executing program cannot fit in the physical memory.

9)  What is thrashing?
    Thrashing is a phenomenon in virtual memory scheme when the processor spends most of its time in swapping pages, 
    rather than executing instructions.

10) What are the four necessary and sufficient conditions behind the deadlock?
    
    1) Mutual Exclusion Condition: It specifies that the resources involved are non-sharable.

    2) Hold and Wait Condition: It specifies that there must be a process that is holding a resource already allocated to it while waiting for additional resource that are currently being held by other processes.

    3) No-Preemptive Condition: Resources cannot be taken away while they are being used by processes.

    4) Circular Wait Condition: It is an explanation of the second condition. It specifies that the processes in the system form a circular list or a chain where each process in
       the chain is waiting for a resource held by next process in the chain.

11) What is a thread?

   A thread is a basic unit of CPU utilization. It consists of a thread ID, 
    program counter, register set and a stack.

12) What is RAID? What are the different RAID levels?

    RAID stands for Redundant Array of Independent Disks. It is used to store the same data redundantly to improve the overall performance.
   
13) What is deadlock? Explain.
     
     Deadlock is a specific situation or condition where two processes are waiting for each other to complete so that they can start. 
     But this situation causes hang for both of them.

14) What is Banker's algorithm?
   
    Banker's algorithm is used to avoid deadlock. It is the one of deadlock-avoidance method.

15) logical address and physical address.
   Logical address space specifies the address that is generated by CPU. On the other hand physical address space specifies the address that is seen by the memory unit.

16) What is semaphore?

    Semaphore is a protected variable or abstract data type that is used to lock the resource being used. The value of the semaphore indicates the status of a common resource.
  
17)  When does trashing occur?
   
    Thrashing specifies an instance of high paging activity. 
    This happens when it is spending more time paging instead of executing.  

18) what is mutex ? 
    In computer programming, a mutual exclusion object (mutex) is a program object that allows multiple program threads to share the same resource, such as file access,
    but not simultaneously

19) Mutex v/s semaphore ?
    mutex is locking mechanism used to synchronize access to a resource.
    Semaphore is signaling mechanism (“I am done, you can carry on” kind of signal). 
   
   


